# General Jekyll Config
source:      .
destination: ../site/note

pygments: true
url: http://note.klb3713.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#072'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: klb3713
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: klb3713
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: klb3713
  email: klbgyx7@gmail.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-41454165-3

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
